In [ ]:
 cd /content/drive/MyDrive/dataset_tps

/content/drive/MyDrive/dataset_tps


In [ ]:
ls

sample_submission.csv      submission_xgb.csv  test.csv.zip  train.csv.zip
sample_submission.csv.zip  test.csv            train.csv


In [ ]:
!unzip train.csv

Archive:  train.csv
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
Archive:  train.csv.zip
replace train.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: 

In [ ]:
!unzip test.csv

Archive:  test.csv.zip
  inflating: test.csv                


In [ ]:
!unzip sample_submission.csv.zip

Archive:  sample_submission.csv.zip
  inflating: sample_submission.csv   


In [ ]:
import numpy as np 
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
from xgboost import XGBRegressor

In [ ]:
from sklearn.linear_model import Ridge

from sklearn.metrics import accuracy_score
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import train_test_split

from sklearn.model_selection import cross_val_score
from sklearn.model_selection import LeaveOneGroupOut

In [ ]:
DF1 = pd.read_csv('train.csv')

DF2 = pd.read_csv('test.csv')

In [ ]:
from sklearn import preprocessing

min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(DF2)
data2 = pd.DataFrame(x_scaled)

In [ ]:
data2 = DF2.copy()

In [ ]:
data1 = DF1.copy()

In [ ]:
data1

id        f0        f1  ...       f98       f99  target
0            0  0.106643  3.594370  ...  0.085974  0.240496       0
1            1  0.125021  1.673360  ... -0.020877  0.024719       0
2            2  0.036330  1.497470  ...  0.124464  0.148209       0
3            3 -0.014077  0.246000  ...  0.040017  0.044873       0
4            4 -0.003259  3.715420  ... -0.012819  0.072798       1
...        ...       ...       ...  ...       ...       ...     ...
599995  599995  0.043008  1.640550  ...  0.049038  0.065804       1
599996  599996  0.137048  4.826860  ...  0.162313  0.085662       0
599997  599997  1.316220  0.502062  ...  0.084864  0.052635       0
599998  599998  0.511918  3.827470  ...  0.061334  0.004179       1
599999  599999  0.179347  3.457390  ...  0.049075  0.044436       1

[600000 rows x 102 columns]

In [ ]:
y = DF1['target']

In [ ]:
x = data1.drop('target',axis=1)

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.70, random_state=314)

In [ ]:
model1v = XGBRegressor(max_depth=5,  n_estimators=1000, learning_rate=0.001, subsample=0.7, alpha=0.5, random_state=314)                           
model1v.fit(x_train, y_train, verbose=0)
oof_pred1 = model1v.predict(x_train)
oof_pred1 = np.clip(oof_pred1, 0.30, y.max())
oof_pred1

[07:55:38] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.


array([0.48942754, 0.5861964 , 0.46706924, ..., 0.4623758 , 0.5360485 ,
       0.48534906], dtype=float32)

In [ ]:
model1v.feature_importances_

array([0.0543354 , 0.        , 0.00639951, 0.00728295, 0.00578629,
       0.00458925, 0.00701164, 0.00380841, 0.        , 0.03196129,
       0.0063529 , 0.00726775, 0.00443164, 0.00407943, 0.00608728,
       0.0063198 , 0.00511369, 0.00437228, 0.00784017, 0.0042588 ,
       0.00543679, 0.00746947, 0.00888044, 0.01532937, 0.        ,
       0.00854631, 0.01697106, 0.00792763, 0.0351282 , 0.00465465,
       0.00408098, 0.00545807, 0.00409499, 0.00475098, 0.        ,
       0.12305379, 0.        , 0.        , 0.00646051, 0.00439228,
       0.00518967, 0.0096779 , 0.019468  , 0.00576957, 0.03706127,
       0.00751526, 0.00661588, 0.        , 0.00595825, 0.00631976,
       0.00622003, 0.0193668 , 0.0051286 , 0.00519509, 0.0061194 ,
       0.00622088, 0.04018771, 0.00360946, 0.0179099 , 0.00579573,
       0.00515443, 0.00986458, 0.00563233, 0.        , 0.00423461,
       0.00499966, 0.00551399, 0.01253776, 0.00587212, 0.00449328,
       0.00493012, 0.00446777, 0.03629209, 0.00313248, 0.00314

In [ ]:
axis_x  = x.columns.values
axis_y = model1v.feature_importances_

plt.style.use('seaborn-whitegrid') 
plt.figure(figsize=(20, 8), facecolor='lightgray')

plt.scatter(axis_x, axis_y, s=120, label='target') 
plt.legend(fontsize=12, loc=2)
plt.show()

In [ ]:
pred1 = model1v.predict(data2)
pred1 = np.clip(pred1, 0.30, y.max())
display(pred1, pred1.shape)
sample = pd.read_csv('sample_submission.csv')
sub_xgb = sample.copy()

sub_xgb['target'] = pred1

array([0.5786368 , 0.5976095 , 0.60417104, ..., 0.4841572 , 0.52164185,
       0.5974802 ], dtype=float32)

(540000,)

In [ ]:
display(sub_xgb)

id    target
0        600000  0.578637
1        600001  0.597610
2        600002  0.604171
3        600003  0.566225
4        600004  0.558486
...         ...       ...
539995  1139995  0.521521
539996  1139996  0.505922
539997  1139997  0.484157
539998  1139998  0.521642
539999  1139999  0.597480

[540000 rows x 2 columns]

In [ ]:
sub = sub_xgb
sub.to_csv("submission_xgb_2.csv",index=False)